Sbom.yml

diff --git a/.github/workflows/sbom.yml b/.github/workflows/sbom.yml
--- a/.github/workflows/sbom.yml
+++ b/.github/workflows/sbom.yml
@@ -1,30 +1,35 @@
-name: Generate and Move SBOM
+name: Snyk Security
 
 on:
   push:
-    branches:
-      - main
+  pull_request:
+
+permissions:
+  contents: read
 
 jobs:
-  generate-sbom:
+  snyk:
+    permissions:
+      contents: read # for actions/checkout to fetch code
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v2
+      - uses: actions/checkout@v3
 
       - name: Install Snyk CLI
-        run: npm install -g snyk
+        run: |
+          npm install -g snyk
 
-      - name: Authenticate Snyk CLI
+      - name: Set up Snyk CLI to check for security issues
         run: snyk auth ${{ secrets.SNYK_API_TOKEN }}
 
-      - name: Generate SBOM
-        run: snyk sbom --format=cyclonedx1.5+json --json-file-output ./sbom/mySBOM.json
+      - name: Run Snyk test
+        run: snyk test
 
-      - name: Commit SBOM file
+      - name: Check for high-severity vulnerabilities
         run: |
-          git config --local user.email "action@github.com"
-          git config --local user.name "GitHub Action"
-          git add sbom/mySBOM.json
-          git commit -m "Generate SBOM file in sbom directory"
-          git push origin main
+          if snyk test --severity-threshold=high; then
+            echo "No high-severity vulnerabilities found."
+          else
+            echo "High-severity vulnerabilities found. Failing the workflow."
+            exit 1
+          fi
